# -*- coding: utf-8 -*-
"""Crout.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVWXEvicdAbKVw2AfM3gDrccrLnluanL
"""

def Crout(A):
    n = A.shape[0]
    U = np.zeros((n, n), dtype=np.double)
    L = np.zeros((n, n), dtype=np.double)
    
    for i in range(n):
        
        L[i, i] = A[i, i] - L[i, :] @ U[:, i]
        
        U[i, i:] = (A[i, i:] - L[i,:i] @ U[:i, i:]) / L[i, i]
        L[(i+1):, i] = (A[(i+1):, i] - L[(i+1):, :] @ U[:, i]) / U[i, i]
    print("Matriz L:")
    print(L)
    print("Matriz U:")
    print(U)
    print("Matriz A como producto LU:")
    print(np.dot(L,U))


A = np.array([[1, 4, 5], [6, 8, 22], [32, 5., 5]])
Crout(A)