# -*- coding: utf-8 -*-
"""Doolittle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSKDnhdnYa_Aw2S64axnfy9Gcgd0oE5-
"""

import numpy as np
def Doolittle(A):
    n = A.shape[0]
    U = np.zeros((n, n), dtype=np.double)
    L = np.eye(n, dtype=np.double)
    for i in range(n):   
        U[i,i:] = A[i,i:] - L[i,:i] @ U[:i,i:]
        L[(i+1):,i] = (A[(i+1):,i] - L[(i+1):,:] @ U[:,i]) / U[i,i]
    return  "Matriz L", L,  "Matriz U", U

A = np.array([[1, 4, 5], [6, 8, 22], [32, 5., 5]])
Doolittle(A)